# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto_sample.proto\"U\n\x10InferenceRequest\x12\x11\n\timg_bytes\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\"\"\n\x0eInferenceReply\x12\x10\n\x08\x64istance\x18\x01 \x01(\x05\x32H\n\x15\x41I_OnlineClassMonitor\x12/\n\x07process\x12\x11.InferenceRequest\x1a\x0f.InferenceReply\"\x00\x62\x06proto3')



_INFERENCEREQUEST = DESCRIPTOR.message_types_by_name['InferenceRequest']
_INFERENCEREPLY = DESCRIPTOR.message_types_by_name['InferenceReply']
InferenceRequest = _reflection.GeneratedProtocolMessageType('InferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEREQUEST,
  '__module__' : 'proto_sample_pb2'
  # @@protoc_insertion_point(class_scope:InferenceRequest)
  })
_sym_db.RegisterMessage(InferenceRequest)

InferenceReply = _reflection.GeneratedProtocolMessageType('InferenceReply', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEREPLY,
  '__module__' : 'proto_sample_pb2'
  # @@protoc_insertion_point(class_scope:InferenceReply)
  })
_sym_db.RegisterMessage(InferenceReply)

_AI_ONLINECLASSMONITOR = DESCRIPTOR.services_by_name['AI_OnlineClassMonitor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERENCEREQUEST._serialized_start=22
  _INFERENCEREQUEST._serialized_end=107
  _INFERENCEREPLY._serialized_start=109
  _INFERENCEREPLY._serialized_end=143
  _AI_ONLINECLASSMONITOR._serialized_start=145
  _AI_ONLINECLASSMONITOR._serialized_end=217
# @@protoc_insertion_point(module_scope)
